import './globals.css'
import { Golos_Text } from 'next/font/google'
import Header from '@/components/Header/Header'

const golos = Golos_Text({ subsets: ['latin', 'cyrillic'], weight: ['400', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={golos.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
